databases:
  - name: taskbox
    databaseName: taskbox
    user: taskbox_user
    plan: free

services:
  - type: web
    name: taskbox
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taskbox
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    plan: free